title: SCHH Commons

description: Community-supported resources for Sun City Hilton Head (SCHH)

author:
  name: SCHH Commons Admin
  email: admin@SCHH-Commons.org

github:
  owner_name: schh-commons
  repository_name: schh-commons.github.io
  source:
    branch: main

nav_pages:
  - _pages/index.md
  - _articles/index.md
  - _podcasts/index.md
  - _pages/about.md
  - _pages/contact.md

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  podcasts:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:collection/:path/

show_excerpts: true
show_rss_feed: true
max-width: 1000px

footer:
  show_github_link: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
